<a href="https://colab.research.google.com/github/ShatakshiR/PythonDemo/blob/master/numpy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import numpy
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# len --> Total number of rows
len(a)

3

In [ ]:
a.shape

(3,)

In [ ]:
a.size

3

In [ ]:
#Two dimensional array
b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# shape - no. of rows, no. of columns
b.shape


(2, 3)

In [ ]:
#size - Total no. of elements
b.size

6

In [ ]:
a = np.array([10,20,30])
b = np.array([40,80,100])
print(a)
print(b)

[10 20 30]
[ 40  80 100]


In [ ]:
#Sum of array
sum =np.sum([a,b])
print(sum)

280


In [ ]:
# Sum across axis=0 (x-axis)
sum = np.sum([a,b],axis = 0)
print(sum)

[ 50 100 130]


In [ ]:
# Sum across axis=1 (y-axis)
sum = np.sum([a,b],axis = 1)
print(sum)

[ 60 220]


In [ ]:
#Subtract
subtract = np.subtract(b,a)
print(subtract)

[30 60 70]


In [ ]:
#multiply
multiply = np.multiply(a,b)
print(multiply)

[ 400 1600 3000]


In [ ]:
#divide
divide = np.divide(b,a)
print(divide)

[4.         4.         3.33333333]


In [ ]:
#exponential - it will increase the value by the exponential of the given number
a = np.array([1,2,3,4,5])
exponential = np.exp(a)
exponential

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
#power raised
np.power(a,3)


array([  1,   8,  27,  64, 125])

In [ ]:
#Square root
b = [121, 625, 729, 521, 2025]
np.sqrt(b)

array([11.        , 25.        , 27.        , 22.82542442, 45.        ])

In [ ]:
#Sine
np.sin(30 * 3.14/180)

0.4997701026431024

In [ ]:
#cos
np.cos(60 * 3.14/180)

0.5004596890082058

In [ ]:
import math

In [ ]:
math.pi

3.141592653589793

In [ ]:
#aggregate
a = [1,2,3,7,8,9,10,11]
print('Sum: ', str(np.sum(a)))
print('Minimum Value: ', str(np.min(a)))
print('Maximum Value: ', str(np.max(a)))
print('Mean Value: ', str(np.mean(a)))
print('Median Value: ', str(np.median(a)))
print('Standard Deviation: ', str(np.std(a)))

Sum:  51
Minimum Value:  1
Maximum Value:  11
Mean Value:  6.375
Median Value:  7.5
Standard Deviation:  3.6033838263498934


In [ ]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]

In [ ]:
#Comparison
#Array comparison at element level
np.equal(a,b)

array([False, False,  True])

In [ ]:
#Arraywise element comparison
np.array_equal(a,b)

False

In [ ]:
np.array_equal(a,c)

True

In [ ]:
#Two dimensional array comparision element wise
a = np.array([[1,2,4], [4,5,6]])
b = np.array([[1,2,4], [7,8,9]])
np.equal(a,b)

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
#Horizontal stack
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Vertical stack
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Initialize an array with all zero elements
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Initialize an array with a particular value
np.full([3,4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
z = np.zeros([3,4])
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Indexing
z[2][1] = 3.14
z

array([[0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 3.14, 0.  , 0.  ]])